sudo: required
services:
    - docker

before_install:
    - docker build -t martindockerlover/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run martindockerlover/react-test npm test -- --coverage

after_success:
    - docker build -t martindockerlover/multi-client ./client
    - docker build -t martindockerlover/multi-nginx ./nginx
    - docker build -t martindockerlover/multi-server ./server
    - docker build -t martindockerlover/multi-worker ./worker
    # log in to the docker CLI
    - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin    
    # Take those impages and push them to docker hub
    - docker push martindockerlover/multi-client
    - docker push martindockerlover/multi-nginx
    - docker push martindockerlover/multi-server
    - docker push martindockerlover/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-515036077391
    bucket_path: docker-multi
    on: 
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
      
